<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJiKLhHw\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJiKLhHw/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerJiKLhHw.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerJiKLhHw\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerJiKLhHw\App_KernelDevDebugContainer([
    'container.build_hash' => 'JiKLhHw',
    'container.build_id' => '5c5f12ae',
    'container.build_time' => 1578616922,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerJiKLhHw');
