<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerNxzhsWk\App_KernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerNxzhsWk/App_KernelTestDebugContainer.php') {
    touch(__DIR__.'/ContainerNxzhsWk.legacy');

    return;
}

if (!\class_exists(App_KernelTestDebugContainer::class, false)) {
    \class_alias(\ContainerNxzhsWk\App_KernelTestDebugContainer::class, App_KernelTestDebugContainer::class, false);
}

return new \ContainerNxzhsWk\App_KernelTestDebugContainer([
    'container.build_hash' => 'NxzhsWk',
    'container.build_id' => '75a60180',
    'container.build_time' => 1578617518,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerNxzhsWk');
